### ISSUE TITLE
some errors i don't konw how to deal with 

### ISSUE THREAD

**Issue by ustbboy** [cthissen/Drex-MATLAB#2]
# Hi Christopher,

I am a greenhand to use the matlab,and long for some matlab code for crystallographic orientation especially on HCP material. I am so happy find your code and try to read them.But I encounter a problem about running the code. the errors:

> > Drex
> > Warning: Name is nonexistent or not a directory: Contour 
> > In path at 109
> >   In addpath at 86
> >   In Drex at 95 
> > Warning: Name is nonexistent or not a directory: export_fig 
> > In path at 109
> >   In addpath at 86
> >   In Drex at 96 
> > Warning: Name is nonexistent or not a directory: dispstat 
> > In path at 109
> >   In addpath at 86
> >   In Drex at 97 
> > Warning: Name is nonexistent or not a directory: colormaps 
> > In path at 109
> >   In addpath at 86
> >   In Drex at 98 
> > Warning: Name is nonexistent or not a directory: functions 
> > In path at 109
> >   In addpath at 86
> >   In Drex at 99 
> > 10:02:54 Looping over timesteps:  
> > 10:03:10 finished
> > Error using fprintf
> > Invalid file identifier.  Use fopen to generate a valid file identifier.

 Error in Drex>writelpotofile (line 415)
    fprintf(fid,'%7.3f %7.3f %7.3f %01.5f\n', LPO.Final.eulerAngles(i,:)*180/pi, LPO.Final.volumeFraction(i));

 Error in Drex (line 309)
writelpotofile(LPO,Flow,Grain);
8.3.0.532 (R2014a)  window7

**Comment by cthissen** [comment]
Hello ustbboy, 

The matlab code is setup to simulate olivine crystal evolutions under different types of deformation. Olivine is an orthorhombic mineral with a specific set of slip systems. Are you planning to try use the code to model hcp metals? That will require some modifications. 

Thanks for letting me know about the errors. I'll take a look. 

Best, 
Chris

**Comment by cthissen** [comment]
Hi ustbboy,

Thanks again for pointing out this bug. Everything should work now. 

Chris

**Comment by ustbboy** [comment]
Hi Christopher,
Thank you for your reply.

ustboy
